#!/usr/bin/env python3
"""
B4 — 웹앱 빌드
- outputs/quizzes.json + state.yaml(ingredients/topics) → webapp/data.js
- outputs/images/ → webapp/images/ 복사
- 누락 이미지 검증 (텍스트 다운그레이드)
- file:// 프로토콜 직접 동작 (서버 불필요)
"""
import os, sys, json, shutil
from pathlib import Path
from datetime import datetime

os.environ.setdefault("PYTHONIOENCODING", "utf-8")
sys.stdout.reconfigure(encoding="utf-8")
import yaml

ROOT = Path(__file__).resolve().parent.parent
QUIZZES = ROOT / "outputs" / "quizzes.json"
STATE = ROOT / "state.yaml"
IMAGES_SRC = ROOT / "outputs" / "images"
WEBAPP = ROOT / "webapp"
DATA_JS = WEBAPP / "data.js"
IMAGES_DST = WEBAPP / "images"


def main():
    if not QUIZZES.exists():
        print(f"❌ {QUIZZES} not found")
        sys.exit(1)
    if not STATE.exists():
        print(f"❌ {STATE} not found")
        sys.exit(1)

    data = json.loads(QUIZZES.read_text(encoding="utf-8"))
    state = yaml.safe_load(STATE.read_text(encoding="utf-8"))

    # data.js에 임베드할 정보
    data["ingredients"] = state.get("ingredients", [])
    data["topics"] = state.get("topics", [])
    data["styles"] = state.get("styles", [])
    data["reward_types"] = state.get("reward_types", [])

    # 이미지 복사
    IMAGES_DST.mkdir(parents=True, exist_ok=True)
    copied = 0
    if IMAGES_SRC.exists():
        for img in IMAGES_SRC.iterdir():
            if img.is_file() and img.suffix.lower() in (".webp", ".png", ".jpg", ".jpeg"):
                shutil.copy2(img, IMAGES_DST / img.name)
                copied += 1

    # image style 문제의 image_path 검증·정규화
    missing = []
    for q in data["quizzes"]:
        if q.get("style") == "image":
            qid = q["id"]
            # 우선순위: q-extra-image-XX.{webp,png,jpg}
            found = None
            for ext in (".webp", ".png", ".jpg", ".jpeg"):
                cand = IMAGES_DST / f"{qid}{ext}"
                if cand.exists():
                    found = f"images/{cand.name}"
                    break
            if found:
                q["image_path"] = found
            else:
                q["image_path"] = None
                missing.append(qid)

    if missing:
        print(f"⚠️  이미지 누락 {len(missing)}개 (image_path=null로 표시):")
        for qid in missing[:8]:
            print(f"     {qid}")
        if len(missing) > 8:
            print(f"     ... 외 {len(missing)-8}개")

    # data.js 생성
    js = f"// auto-generated by 03_build_webapp.py at {datetime.now().isoformat()}\n"
    js += f"window.QUIZZES = {json.dumps(data, ensure_ascii=False, indent=2)};\n"
    DATA_JS.write_text(js, encoding="utf-8")

    print(f"\n✅ webapp built")
    print(f"   - quizzes:    {len(data['quizzes'])}")
    print(f"   - ingredients:{len(data['ingredients'])}")
    print(f"   - topics:     {len(data['topics'])}")
    print(f"   - images:     {copied} copied to webapp/images/")
    print(f"   - data.js:    {DATA_JS} ({DATA_JS.stat().st_size:,} bytes)")
    print(f"\n💡 다음: webapp/index.html 더블클릭으로 동작 확인")


if __name__ == "__main__":
    main()
